[window]
padding = { x = 10, y = 5 }
dynamic_padding = true
opacity = 0.90


[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 14


[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[terminal]

[terminal.shell]
program = "tmux"
args = ["new-session", "-A", "-D", "-s", "Home"]
